AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcCidrBlock:
    Type: String
    Description: CIDR block for the VPC
    Default: '10.0.0.0/16'
  PublicSubnet1CidrBlock:
    Type: String
    Description: CIDR block for the first public subnet
    Default: '10.0.0.0/24'
  PublicSubnet2CidrBlock:
    Type: String
    Description: CIDR block for the second public subnet
    Default: '10.0.1.0/24'
  PrivateSubnet1CidrBlock:
    Type: String
    Description: CIDR block for the first private subnet
    Default: '10.0.2.0/24'
  PrivateSubnet2CidrBlock:
    Type: String
    Description: CIDR block for the second private subnet
    Default: '10.0.3.0/24'
  PrivateSubnet3CidrBlock:
    Type: String
    Description: CIDR block for the third private subnet
    Default: '10.0.4.0/24'
  PrivateSubnet4CidrBlock:
    Type: String
    Description: CIDR block for the fourth private subnet
    Default: '10.0.5.0/24'
  PrivateSubnet5CidrBlock:
    Type: String
    Description: CIDR block for the fifth private subnet
    Default: '10.0.6.0/24'
  PrivateSubnet6CidrBlock:
    Type: String
    Description: CIDR block for the sixth private subnet
    Default: '10.0.7.0/24'
