AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for an RDS DB cluster.

Parameters:
  DBInstanceID:
    Default: p1dbinstance
    Description: ID for the RDS database instance. Used for identification purposes.
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and must not end with a hyphen or contain two consecutive hyphens.
  DBName:
    Description: My database name.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
    Default: p1db
  DBInstanceClass:
    Description: Select the instance type for your application database.
    Type: String
    Default: db.m5d.large
    AllowedValues:
      - db.m5d.large
      - db.m5d.xlarge
      - db.m5d.2xlarge
      - db.m5d.4xlarge
      - db.m5d.8xlarge
      - db.m5d.12xlarge
      - db.m5d.16xlarge
      - db.m5d.24xlarge
  MultiAZ:
    Description: Create replica in a different Availability zone.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: Multi-AZ must be true or false.
  DBAllocatedStorage:
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '8'
    MaxValue: '65536'
    ConstraintDescription: Must be between 20 and 65536 GiB.
    Default: 100
  StorageType:
    Description: The type of storage.
    Type: String
    Default: gp2
    AllowedValues:
      - gp2
      - io1
    ConstraintDescription: Must be a valid storage type.
  Iops:
    Description: The amount of provisioned IOPS. Setting this implies a gp2 storage type.
    Type: Number
    MinValue: '100'
    MaxValue: '3200'
    ConstraintDescription: Must be between 100 and 3200.
    Default: 1000
  MasterUsername:
    Description: Username for MySQL database access
    NoEcho: true
    Type: AWS::SSM::Parameter::Value<SecureString>
    Default: /p1db/username
  MasterUserPassword:
    Description: Password MySQL database access
    Type: AWS::SSM::Parameter::Value<SecureString>
    Default: /p1db/password

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup 
    Properties: 
      DBSubnetGroupName: rds-subnet-group
      DBSubnetGroupDescription: My RDS Subnet Group
      SubnetIds: 
        - !ImportValue P1-PrivateSubnet3ID
        - !ImportValue P1-PrivateSubnet4ID
        - !ImportValue P1-PrivateSubnet5ID
        - !ImportValue P1-PrivateSubnet6ID
      Tags: 
        - Key: Name
          Value: P1-dbsubnetgroup
  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Parameter group for cluster
      Family: mysql8.0
      Parameters:
        character_set_server: utf8mb4
        collation_server: utf8mb4_unicode_ci
      Tags:
        - Key: Name
          Value: p1-cluster-parameter-group 

  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      Engine: mysql
      AllocatedStorage: !Ref DBAllocatedStorage 
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue P1-DBSecurityGroupID
      DBClusterInstanceClass: !Ref DBInstanceClass
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      StorageType: !Ref StorageType
      Iops: !Ref Iops

Outputs:
  DBClusterEndpointAddress:
    Description: Endpoint for the database
    Value: !GetAtt DBCluster.Endpoint.Address
    Export:
      Name: P1-DBClusterEndpointAddress
  DBClusterEndpointPort:
    Description: Port for the database
    Value: !GetAtt DBCluster.Endpoint.Port
    Export:
      Name: P1-DBClusterEndpointPort
